replicaCount: 1

podAnnotations:
  linkerd.io/inject: enabled

deployment:
  annotations:
    sidecar.jaegertracing.io/inject: jaeger-dev

jaeger:
  collector_host: dns:///jaeger-dev-collector-headless.observability:14250

image:
  repository: registry.happytravel.com/gifu
  tag: latest
  pullPolicy: Always
imagePullSecrets:
  - name: travel-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false 
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  grpc:
    port: 5101
  metrics:
    port: 60001
  healthchecks:
    port: 60000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
  hosts:
    - host: gf-dev.happytravel.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: happytravel-tls
     hosts:
       - gf-dev.happytravel.com

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - gifu
      topologyKey: "kubernetes.io/hostname"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

metrics:
  enabled: false
  podMonitor:
    enabled: false

env:
  ASPNETCORE_URLS: http://*:80
  ASPNETCORE_ENVIRONMENT: "Development"
  HTDC_VAULT_ENDPOINT: "https://vault.dev.happytravel.com/v1/"
  HTDC_GIFU_SENTRY_ENDPOINT: "https://9159b1440e3f4215aa9de0cba5849cfd:f2fbb9108841429a9cdd7058c1372cd0@sentry.happytravel.com/43"
  HTDC_REDIS_HOST: "redis-gifu"
  JAEGER_AGENT_HOST: "localhost"
  JAEGER_AGENT_PORT: "6831"
  CONSUL_HTTP_ADDR: "https://consul-dev.happytravel.com/"
