// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace HappyTravel.Gifu.Data.CompiledModels
{
    [DbContext(typeof(GifuContext))]
    public partial class GifuContextModel : RuntimeModel
    {
        static GifuContextModel()
        {
            var model = new GifuContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static GifuContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
